In [4]:
# markov chain stable state, 稳定分布，收敛性
import numpy as np


def markov_stable(pi_0):
    transmit = [[0.9,    0.075,  0.025],
                       [0.15,  0.8,      0.05],
                       [0.25,  0.25,    0.5]]

    pi_m = np.matrix(pi_0, dtype=float)
    transmit_m = np.matrix(transmit, dtype=float)
    for i in range(100):
        pi_m = pi_m*transmit_m
        # print("Current round:" , i+1)
        #print(pi_1_m)
        
    return pi_m 
        
pi_0 = [[0.3, 0.4, 0.3]]
stable = markov_stable(pi_0)
print(stable)

pi_0 = [[0.7, 0.1, 0.2]]
stable = markov_stable(pi_0)
print(stable)

[[0.625  0.3125 0.0625]]
[[0.625  0.3125 0.0625]]


In [6]:
# pi*P = pi
transmit = [[0.9,    0.075,  0.025],
                       [0.15,  0.8,      0.05],
                       [0.25,  0.25,    0.5]]

matrix = np.matrix(transmit, dtype=float)
for i in range(10):
    matrix = matrix*matrix
    print("Current round:" , i+1)
    print(matrix)

Current round: 1
[[0.8275  0.13375 0.03875]
 [0.2675  0.66375 0.06875]
 [0.3875  0.34375 0.26875]]
Current round: 2
[[0.73555  0.212775 0.051675]
 [0.42555  0.499975 0.074475]
 [0.51675  0.372375 0.110875]]
Current round: 3
[[0.65828326 0.28213131 0.05958543]
 [0.56426262 0.36825403 0.06748335]
 [0.5958543  0.33741675 0.06672895]]
Current round: 4
[[0.62803724 0.30972343 0.06223933]
 [0.61944687 0.3175772  0.06297594]
 [0.6223933  0.3148797  0.062727  ]]
Current round: 5
[[0.62502532 0.31247685 0.06249783]
 [0.6249537  0.31254233 0.06250397]
 [0.62497828 0.31251986 0.06250186]]
Current round: 6
[[0.625  0.3125 0.0625]
 [0.625  0.3125 0.0625]
 [0.625  0.3125 0.0625]]
Current round: 7
[[0.625  0.3125 0.0625]
 [0.625  0.3125 0.0625]
 [0.625  0.3125 0.0625]]
Current round: 8
[[0.625  0.3125 0.0625]
 [0.625  0.3125 0.0625]
 [0.625  0.3125 0.0625]]
Current round: 9
[[0.625  0.3125 0.0625]
 [0.625  0.3125 0.0625]
 [0.625  0.3125 0.0625]]
Current round: 10
[[0.625  0.3125 0.0625]
 [0.625  0.31